services:
  - docker

before_install:
  - docker build -t leachdeniro/react-test -f ./client/Dockerfile.dev ./client

srcipt:
  - docker run -e CI=true leachdeniro/react-test npm test

after_success:
  - docker build -t leachdeniro/multi-client ./client
  - docker build -t leachdeniro/multi-nginx ./nginx
  - docker build -t leachdeniro/multi-server ./server
  - docker build -t leachdeniro/multi-worker ./worker
  #login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push leachdeniro/multi-client
  - docker push leachdeniro/multi-nginx
  - docker push leachdeniro/multi-server
  - docker push leachdeniro/multi-worker 